sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - stable

cache: yarn

notifications:
  email: false

script:
  - npm run lint
  - npm run type-check
  - npm test

after_success:
  - npm run report-coverage
